### PR TITLE
add starname project

### PR DESCRIPTION
**Pull request by gabrielasf**

### CODE REVIEW

**Comment by ligi** [comment]
where is the WalletConnect integration in the project?

**Comment by antoineherzog** [comment]
Hi Ligi!
I hope you are well :)
We integrated Wallet Connect inside the Starname Manager:
https://app.starname.me/
We use Wallet Connect to synchronise all the wallet addresses directly into a starname (so you don't need to copy/past any address that's pretty cool)
https://www.youtube.com/watch?v=rpiaCkalL08&feature=emb_title
There is another topic that I would like to talk to. We started to work on the asset directory based on CAIP-19 (https://github.com/iov-one/asset-directory). Maybe we can chat this week about it?*
Have a good day
Antoine

**Comment by ligi** [comment]
> Hi Ligi!
> I hope you are well :)

I am wellIsh (for 2020) - hope you are too.

> We integrated Wallet Connect inside the Starname Manager:
> https://app.starname.me/

cool - thanks for the info!
maybe the URL in the PR then should be https://app.starname.me

> We use Wallet Connect to synchronise all the wallet addresses directly into a starname (so you don't need to copy/past any address that's pretty cool)
> https://www.youtube.com/watch?v=rpiaCkalL08&feature=emb_title

ah I see - but seems you still need a ledger to go so far? Do you plan on supporting WC in a way so ledger is no more needed?

> There is another topic that I would like to talk to. We started to work on the asset directory based on CAIP-19 (https://github.com/iov-one/asset-directory). Maybe we can chat this week about it?*

this week is a bit full - next week would work better for me

> Have a good day

u2

**Comment by antoineherzog** [comment]
I fixed the PR and put the URL of the application.

Starname Manager is working with our Cosmos SDK chain the IOV Name Service. To sign Transactions, the current version of WalletConnect supports only Ethereum based chain. So at the moment, we only support Wallet Connect as a way to synchronise crypto-addresses with your starname from Ethereum Wallets and also Binance and Cosmos Wallets (not to sign transactions at the moment). 

We would be happy to add Wallet Connect as a way to sign-in when Wallet Connect becomes multi-chain with the version 2.0 I believe.

Ok sounds good for next week, I will write you on RIOT!

**Pull request merged**
