### PR TITLE
Remove gnosis safe

### PR DESCRIPTION
**Pull request by ligi**
does not support WC anymore :-(
don't shoot the messenger - was surprised myself

### CODE REVIEW

**Comment by bmann** [comment]
@ligi the version I have on iOS still has it integrated.

**Comment by pedrouid** [comment]
Could you comment on this?
cc @rmeissner @tschubotz @DmitryBespalov @sche

**Comment by ligi** [comment]
@bmann must be a legacy version then - AFAIK (can't verify it for iOS - just did for android) it shoud also be gone there in the latest version

**Comment by DmitryBespalov** [comment]
Hi, the legacy version does not support the mobile wallet connect  because we have  implemented  the very  first wallet connect  version, but then it changed later and we have deprecated the iOS app, so it didn't make sense to implement the released mobile WC version.

The WC will be implemented in  the new mobile app in the future (2-3 months). Meanwhile, the Gnosis Safe web supports  the wallet connect.

**Comment by DmitryBespalov** [comment]
So, for now, I approve this change. We'll add it back when we have it in the app.

**Comment by pedrouid** [comment]
Well this seems to be a temporary situation... I don't think it's necessary to remove it from the website since Gnosis Safe was one of the first wallets to support and also a top code contributor to the project

Look forward to see the WalletConnect support being re-integrated in the near future

**Comment by ligi** [comment]
Hm - I talked to an engineer on the android team (mainly because I need PRs in https://github.com/WalletConnect/kotlin-walletconnect-lib/pulls merged) and it sounded differently. But I have no strong opinion on removing it - just thought it's a good idea not to confuse users showing a wallet has support when it is gone ..

**Comment by tschubotz** [comment]
Hey, just adding a bit more context / explanation:

- @bmann is right, the old ("legacy") Gnosis Safe mobile apps have WalletConnect. But we are phasing those out.
- @ligi is also right, the new mobile apps, don't yet have WalletConnect. Neither on Android nor on iOS.

Reason for the latter is, that we made a bit if a switch earlier this year to make our web interface at https://gnosis-safe.io/app the central point for now. High value asset management is still more of a web/desktop use case. At least right now.

We still love WalletConnect, it's basically the only "standard" that all dapps support besides Metamask. We actually will ship WalletConnect support in the Gnosis Safe Multisig web interface this or next week (cf. gnosis/safe-react/issues#1239). Then users would be able to connect their Safe to dapps. (And not only 3rd party owner wallets to their Safe). So this would re-qualify the Gnosis Safe as wallet that supports WalletConnect I think. :) Just not on mobile, yet. 

Ligi is also right though that we don't have WalletConnect support on the mobile roadmap, yet. That is because currently users anyway need to use the web interface for making txs. So we first plan to add signing functionality and other things on mobile before thinking about mobile WalletConnect again, currently.

**Comment by pedrouid** [comment]
I guess this basically concludes that in the website we should do the following:
- remove Gnosis Safe from Wallets page
- add Gnosis Multisig to Apps page

Additionally as part of the walletconnect-monorepo changes, it should also include:
- remove Gnosis Safe from mobile-registry

Are we all in agreement with these changes?

**Comment by tschubotz** [comment]
> * remove Gnosis Safe from Wallets page

With the upcoming WalletConnect feature to connect the Gnosis Safe Multisig (the wallet) to a dapp, doesn't the Gnosis Safe Multisig qualify for the "wallet" section as well?

> * add Gnosis Multisig to Apps page

👍 

> remove Gnosis Safe from mobile-registry

I have no insight into how many users of the old app use this, but I think removing it would be the best moving forward. 👍

**Comment by bmann** [comment]
I would remove nothing, and add Gnosis Multisig to apps. 

We shouldn’t aim for absolute correctness (it’s not a lookup table), but rather to celebrate and highlight supporters and implementors. 

Gnosis 😍 WalletConnect and vice versa ;)

**Comment by pedrouid** [comment]
I agree @bmann that we should be celebrating and highlighting project supporters but perhaps that warrants instead a separate section on the website specially on the homepage. As @ligi mentioned correctly this page is used as reference by users to install a WalletConnect-supported wallet.

Regarding whether Gnosis Multisig should be present on the Wallets page (@tschubotz) the way it's referenced between Wallets and Dapps can be seen as signers and applications, respectively.

Gnosis Multisig web interface would sit next to Dapps just like MyCrypto. It currently doesn't have signing capabilities that can be used to sign transactions and message requests from other applications.

New Proposed Changes:
* remove Gnosis Safe from Wallets page
* add Gnosis Multisig to Apps page
* add Project Supporters sections on the Home page

**Comment by tschubotz** [comment]
> Regarding whether Gnosis Multisig should be present on the Wallets page (@tschubotz) the way it's referenced between Wallets and Dapps can be seen as signers and applications, respectively.
> 
> Gnosis Multisig web interface would sit next to Dapps just like MyCrypto. It currently doesn't have signing capabilities that can be used to sign transactions and message requests from other applications.

The Gnosis Safe Multisig as contract wallet would act as "signer" in that case though, right? (I know not technically an ECDSA signer like an EOA but the smart contract wallet is still the actor.) Here's some details on how this would work in a v1: https://help.gnosis-safe.io/en/articles/4356253-how-to-use-walletconnect-with-the-gnosis-safe-multisig (Not yet live, but that'll be the accompanying help center article.)

I also see your point though of Gnosis Safe Multisig being a dapp and the analogy to MyCrypto. I have no super strong opinion on this and am fine either way!



> New Proposed Changes:
> 
>     * remove Gnosis Safe from Wallets page
> 
>     * add Gnosis Multisig to Apps page
> 
>     * add Project Supporters sections on the Home page

👍

**Comment by pedrouid** [comment]
Well that's definitely a novel pattern but it's legit as long as Gnosis Safe Multisig is able to successfully resolve at least the eth_sendTransaction which seems to be the case. In that case I would list Gnosis Safe Multisig on both pages with the new logo (monochrome one) and simply remove it from the mobile linking registry

On another note, looking at that helper document I can see from the screenshots that you are using a different name ("SafeConnect") instead of WalletConnect, could you change this? The whole point of the standard is to provide a consistent experience that is quickly recognizable by users and it's important to protect this property as an open protocol.

Bluetooth is always called Bluetooth. There is no such thing as Samsungtooth or Appletooth.

**Comment by rmeissner** [comment]
@pedrouid that document refers to a prototype the final version is "WalletConnect" (see https://safe-team.dev.gnosisdev.com/app/#/safes/0x2A6936131e34287372769C82e4bcFFa42845067F/apps)

**Comment by tschubotz** [comment]
@pedrouid Not worries. Like Richard said, it'll be called WalletConnect, not Safe connect, for the exact reasons you mentioned :)

**Comment by pedrouid** [comment]
I've made all changes related to this issue. Check out the new home page now featuring top funders and top contributors

I will be releasing a new UI for the QR Code modal soon as well which will remove the Gnosis Safe deep link and add a "Copy to Clipboard" feature

**Comment by AVGolden** [comment]
0x4C549990A7eF3FEA8784406c1EECc98bF4211fA5https://github.com/ampedandwired/html-webpack-pluginhttps://github.com/ampedandwired/html-webpack-pluginhttps://github.com/ampedandwired/html-webpack-pluginhttps://github.com/ampedandwired/html-webpack-pluginhttps://github.com/ampedandwired/html-webpack-pluginhttps://github.com/ampedandwired/html-webpack-plugineth to Microsoft account pointeth to Microsoft account point

**Pull request closed without merging**
