### PR TITLE
Add ViaWallet to list of wallets

### PR DESCRIPTION
**Pull request by Super-JJ**

### CODE REVIEW

**Comment by gthreadgill** [comment]
Add coinbase wallet and Klever wallet

**Comment by Super-JJ** [comment]
> Add coinbase wallet and Klever wallet

What does this mean?

**Comment by pedrouid** [comment]
Hey @Super-JJ, please dismiss that comment. I'm not aware of this user and it's also not a contributor so they must be referring to WalletConnect in general

Could you review and solve the merge conflict in order for me to merge this?

Thanks

**Comment by Super-JJ** [comment]
@pedrouid Ok, the conflict has been resolved, thanks

**Pull request merged**
